In [1]:
import numpy as np # 日常调包,np是缩写

In [2]:
array = np.array(([1,2,3],[2,3,4])) # numpy的 array（）列表转为矩阵
print(array)

[[1 2 3]
 [2 3 4]]


In [5]:
print('number of dim:',array.ndim)# 维度
print('shape :',array.shape) # row行数 and column列数
print('size', array.size) # 矩阵的元素个数  

number of dim: 2
shape : (2, 3)
size 6


In [6]:
a = np.array([2,23,4]) # List 1d
print(a)

[ 2 23  4]


# 指定数据类型


In [8]:
a = np.array([2,23,4],dtype=np.int) # int64
print(a.dtype)

int64


In [9]:
a = np.array([2,23,4],dtype=np.int32) # int32
print(a.dtype)

int32


In [10]:
a = np.array([2,23,4],dtype=np.float) # float64
print(a.dtype)

float64


In [11]:
a = np.array([2,23,4],dtype=np.float32) # float32
print(a.dtype)

float32


# 创建矩阵数据

In [15]:
b = np.array(([19,88,29],[20,18,1])) # 二维矩阵，2行3列
print(b)

[[19 88 29]
 [20 18  1]]


In [16]:
# 创建全零数组

c = np.zeros((3,4)) # 3 rows , 4 columns
c 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
d = np.ones((2,3),dtype = np.int)
d

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
d = np.empty((3,4)) # 空值，其实都接近零，3row 4column
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
a = np.arange(10,20,2) # 10-19的数据，2步长
b = np.arange(20,100,20)
print(a, b)

[10 12 14 16 18] [20 40 60 80]


In [22]:
a = np.arange(20).reshape((4,5)) # reshape()
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
# 用 linspace 创建线段型数据

a = np.linspace(1, 10, 20)# 开始端1，结束端10，且分割成20个数据，生成线段
b = np.linspace(1,29,15)
c = np.linspace(10,20,2)
print(a)
print(b)
print(c)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29.]
[10. 20.]


In [30]:
b = np.linspace(1,29,15).reshape((5,3))
b

array([[ 1.,  3.,  5.],
       [ 7.,  9., 11.],
       [13., 15., 17.],
       [19., 21., 23.],
       [25., 27., 29.]])

In [31]:
import numpy as np
a=np.array([10,20,30,40])   # array([10, 20, 30, 40])
b=np.arange(4)

print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


In [32]:
c = a + b
c

array([10, 21, 32, 43])

In [33]:
c = a - b
c

array([10, 19, 28, 37])

In [36]:
c = a * b
c

array([  0,  20,  60, 120])

In [34]:
c = b**2
c

array([0, 1, 4, 9])

In [38]:
# Numpy中具有很多的数学函数工具，比如三角函数等

c = 10 * np.sin(a)
c

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [40]:
print(b<3) # 除了函数应用外，在脚本中对print函数进行一些修改可以进行逻辑判断

[ True  True  True False]


In [51]:
a = np.array([[1,1],[0,1]])
b = np.arange(4).reshape((2,2))

print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [52]:
c_dot_2 = a.dot(b)
c_dot_2

array([[2, 4],
       [2, 3]])

In [53]:
c_dot = np.dot(a, b)
c_dot

array([[2, 4],
       [2, 3]])

In [55]:
a=np.random.random((2,4))
a

array([[0.18996536, 0.56326054, 0.06329861, 0.66325886],
       [0.96658954, 0.33350635, 0.3007472 , 0.76658659]])

In [56]:
print(np.sum(a))
print(np.min(a))
print(np.max(a))

3.847213043424304
0.06329860562789069
0.9665895438410694


In [57]:
print("a = ",a)
print("sum = ",np.sum(a, axis=1))
print("min = ",np.min(a, axis=0))
print("max = ",np.max(a, axis=1))

a =  [[0.18996536 0.56326054 0.06329861 0.66325886]
 [0.96658954 0.33350635 0.3007472  0.76658659]]
sum =  [1.47978336 2.36742968]
min =  [0.18996536 0.33350635 0.06329861 0.66325886]
max =  [0.66325886 0.96658954]


In [77]:
a = np.arange(2,14).reshape((3,4))
print(np.argmin(a))
print(np.argmax(a))

0
11


In [78]:
print(np.mean(a))
print(np.average(a))

7.5
7.5


In [79]:
print(a.mean())
print(np.mean(a))

7.5
7.5


In [80]:
print(np.cumsum(a)) # 生成的每一项矩阵元素均是从原矩阵首项累加到对应项的元素之和。

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [81]:
print(np.diff(a))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [82]:
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [83]:
print(np.nonzero(a))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [76]:
a = np.arange(14,2, -1).reshape((3,4)) 
print(np.sort(a))

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [84]:
a.T

array([[ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12],
       [ 5,  9, 13]])

In [85]:
print(a)
print(np.clip(a,5,9))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


In [93]:
a = np.arange(3,15)
a[2]

5

In [94]:
a[:5]

array([3, 4, 5, 6, 7])

In [95]:
a[5:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [97]:
a= a.reshape((3,4))
a

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [98]:
a[2][1]

12

In [99]:
a[2]

array([11, 12, 13, 14])

In [100]:
a[1, 1:3]

array([8, 9])

In [101]:
for row in a:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [102]:
for column in a.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [105]:
# 迭代输出
print(a.flatten()) 
# flatten是一个展开性质的函数，将多维的矩阵进行展开成1行的数列
# 而flat是一个迭代器，本身是一个object属性

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [106]:
for i in a.flatten():
    print(i)

3
4
5
6
7
8
9
10
11
12
13
14


In [110]:
# 合并

a = np.array([1,1,1])
b = np.array([2,2,2])

c = np.vstack((a, b)) # 上下合并 vertical stack

print(c)

[[1 1 1]
 [2 2 2]]


In [111]:
c.shape

(2, 3)

In [112]:
d = np.hstack((a,b)) #左右合并horizontal stack
print(d)
print(a.shape,d.shape)

[1 1 1 2 2 2]
(3,) (6,)


In [116]:
print(a[np.newaxis, :])
print(a[np.newaxis, :].shape)
print(a[:,np.newaxis])
print(a[:,np.newaxis].shape)

[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]
(3, 1)


In [119]:
a = np.array([1,1,1])[:,np.newaxis]
b = np.array([2,2,2])[:,np.newaxis]
print(a)
print(b)
d = np.hstack((a,b))
print(d.shape)
d

[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]
(3, 2)


array([[1, 2],
       [1, 2],
       [1, 2]])

In [121]:
c = np.concatenate((a,b,b,a),axis = 0)
print(c)
d = np.concatenate((a,b,b,a),axis = 1)
print(d)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [122]:
a = np.arange(12).reshape((3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [123]:
# split array

print(np.split(a, 2, axis = 1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [124]:
print(np.split(a, 3, axis = 0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [126]:
print(np.array_split(a, 3, axis = 1)) # 不等量分割

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [127]:
import pandas as pd

In [128]:
s = pd.Series([1,3,6,np.nan,44,1])
print(s)

0     1.0
1     3.0
2     6.0
3     NaN
4    44.0
5     1.0
dtype: float64


In [133]:
dates = pd.date_range('20160101',periods=6)
df= pd.DataFrame(np.random.randn(6,4),index=dates, columns=['a','b','c','d'])

In [134]:
print(df)

                   a         b         c         d
2016-01-01 -1.651576 -0.077198 -0.358824  0.154984
2016-01-02  1.033267  0.590614  0.261177  0.160977
2016-01-03  0.037900  1.650723  1.106941  0.575682
2016-01-04  0.891988  0.085079 -0.630789 -1.073638
2016-01-05 -1.744333 -2.067776  0.378052 -1.447717
2016-01-06 -1.310605  1.951291  1.680186 -0.696004


DataFrame是一个表格型数据结构

In [136]:
df.describe()

a         b         c         d
count  6.000000  6.000000  6.000000  6.000000
mean  -0.457227  0.355455  0.406124 -0.387619
std    1.272672  1.443056  0.871380  0.801605
min   -1.744333 -2.067776 -0.630789 -1.447717
25%   -1.566333 -0.036629 -0.203824 -0.979229
50%   -0.636353  0.337846  0.319615 -0.270510
75%    0.678466  1.385696  0.924719  0.159479
max    1.033267  1.951291  1.680186  0.575682

In [137]:
print(df['c'],df['b'])

2016-01-01   -0.358824
2016-01-02    0.261177
2016-01-03    1.106941
2016-01-04   -0.630789
2016-01-05    0.378052
2016-01-06    1.680186
Freq: D, Name: c, dtype: float64 2016-01-01   -0.077198
2016-01-02    0.590614
2016-01-03    1.650723
2016-01-04    0.085079
2016-01-05   -2.067776
2016-01-06    1.951291
Freq: D, Name: b, dtype: float64


In [138]:
df1 = pd.DataFrame(np.arange(12).reshape((3,4)))
df1

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [139]:
df2 = pd.DataFrame({'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["test","train","test","train"]),
                    'F' : 'foo'})
                    
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [140]:
df2 = pd.DataFrame({'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["test","train","test","train"]),
                    'F' : 'foo'})
                    
print(df2)


     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [142]:
print(df2.dtypes)

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [143]:
print(df2.index)

Int64Index([0, 1, 2, 3], dtype='int64')


In [144]:
print(df2.columns)

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


In [145]:
print(df2.values)

[[1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']]


In [146]:
print(df2.sort_index(axis=1, ascending=False))

     F      E  D    C          B    A
0  foo   test  3  1.0 2013-01-02  1.0
1  foo  train  3  1.0 2013-01-02  1.0
2  foo   test  3  1.0 2013-01-02  1.0
3  foo  train  3  1.0 2013-01-02  1.0


In [147]:
print(df2.sort_values(by='B'))

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [148]:
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)),index=dates, columns=['A','B','C','D'])

In [152]:
df.A # df['A'] 另一种写法

2013-01-01     0
2013-01-02     4
2013-01-03     8
2013-01-04    12
2013-01-05    16
2013-01-06    20
Freq: D, Name: A, dtype: int64

In [153]:
df['A']

2013-01-01     0
2013-01-02     4
2013-01-03     8
2013-01-04    12
2013-01-05    16
2013-01-06    20
Freq: D, Name: A, dtype: int64

In [155]:
print(df[0:3])

            A  B   C   D
2013-01-01  0  1   2   3
2013-01-02  4  5   6   7
2013-01-03  8  9  10  11


In [154]:
print(df['20130102':'20130104'])

             A   B   C   D
2013-01-02   4   5   6   7
2013-01-03   8   9  10  11
2013-01-04  12  13  14  15


In [156]:
print(df.loc['20130102']) # 根据标签来选择数据 loc
print(df.loc[:,['A','B']]) # :代表所有行

A    4
B    5
C    6
D    7
Name: 2013-01-02 00:00:00, dtype: int64
             A   B
2013-01-01   0   1
2013-01-02   4   5
2013-01-03   8   9
2013-01-04  12  13
2013-01-05  16  17
2013-01-06  20  21


In [157]:
print(df.iloc[3,1]) # 采用位置进行选择 iloc
print(df.iloc[3:5,1:3])
print(df.iloc[[1,3,5],1:3])

13
             B   C
2013-01-04  13  14
2013-01-05  17  18
             B   C
2013-01-02   5   6
2013-01-04  13  14
2013-01-06  21  22


In [158]:
print(df[df.A>8]) # 判断指令 (Boolean indexing) 进行选择

             A   B   C   D
2013-01-04  12  13  14  15
2013-01-05  16  17  18  19
2013-01-06  20  21  22  23


In [159]:
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)),index=dates, columns=['A','B','C','D'])

In [161]:
df.iloc[2,2] = 1111 # 根据索引赋值
df.loc['20130101','B'] = 2222 #根据标签赋值 
df

A     B     C   D
2013-01-01   0  2222     2   3
2013-01-02   4     5     6   7
2013-01-03   8     9  1111  11
2013-01-04  12    13    14  15
2013-01-05  16    17    18  19
2013-01-06  20    21    22  23

In [163]:
df[df.A > 4] = np.nan # 根据条件赋值
df

A       B    C    D
2013-01-01  0.0  2222.0  2.0  3.0
2013-01-02  4.0     5.0  6.0  7.0
2013-01-03  NaN     NaN  NaN  NaN
2013-01-04  NaN     NaN  NaN  NaN
2013-01-05  NaN     NaN  NaN  NaN
2013-01-06  NaN     NaN  NaN  NaN

In [164]:
df.isnull()

A      B      C      D
2013-01-01  False  False  False  False
2013-01-02  False  False  False  False
2013-01-03   True   True   True   True
2013-01-04   True   True   True   True
2013-01-05   True   True   True   True
2013-01-06   True   True   True   True

In [171]:
df = df.fillna(20)

In [172]:
df['F'] = np.nan
df

A       B     C     D   F
2013-01-01   0.0  2222.0   2.0   3.0 NaN
2013-01-02   4.0     5.0   6.0   7.0 NaN
2013-01-03  20.0    20.0  20.0  20.0 NaN
2013-01-04  20.0    20.0  20.0  20.0 NaN
2013-01-05  20.0    20.0  20.0  20.0 NaN
2013-01-06  20.0    20.0  20.0  20.0 NaN

In [173]:
df['E'] = pd.Series([1,2,3,4,5,6], index=pd.date_range('20130101',periods=6)) 

In [174]:
df

A       B     C     D   F  E
2013-01-01   0.0  2222.0   2.0   3.0 NaN  1
2013-01-02   4.0     5.0   6.0   7.0 NaN  2
2013-01-03  20.0    20.0  20.0  20.0 NaN  3
2013-01-04  20.0    20.0  20.0  20.0 NaN  4
2013-01-05  20.0    20.0  20.0  20.0 NaN  5
2013-01-06  20.0    20.0  20.0  20.0 NaN  6

In [175]:
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)),index=dates, columns=['A','B','C','D'])
df.iloc[0,1] = np.nan
df.iloc[1,2] = np.nan

In [176]:
df.dropna(
    axis=0,     # 0: 对行进行操作; 1: 对列进行操作
    how='any'   # 'any': 只要存在 NaN 就 drop 掉; 'all': 必须全部是 NaN 才 drop 
    ) 

A     B     C   D
2013-01-03   8   9.0  10.0  11
2013-01-04  12  13.0  14.0  15
2013-01-05  16  17.0  18.0  19
2013-01-06  20  21.0  22.0  23

In [177]:
df.fillna(0)

A     B     C   D
2013-01-01   0   0.0   2.0   3
2013-01-02   4   5.0   0.0   7
2013-01-03   8   9.0  10.0  11
2013-01-04  12  13.0  14.0  15
2013-01-05  16  17.0  18.0  19
2013-01-06  20  21.0  22.0  23

In [178]:
df.isnull() 

A      B      C      D
2013-01-01  False   True  False  False
2013-01-02  False  False   True  False
2013-01-03  False  False  False  False
2013-01-04  False  False  False  False
2013-01-05  False  False  False  False
2013-01-06  False  False  False  False

In [179]:
#读取csv
data = pd.read_csv('student.csv')

#打印出data
print(data)

    Student ID  name   age  gender
0         1100  Kelly   22  Female
1         1101    Clo   21  Female
2         1102  Tilly   22  Female
3         1103   Tony   24    Male
4         1104  David   20    Male
5         1105  Catty   22  Female
6         1106      M    3  Female
7         1107      N   43    Male
8         1108      A   13    Male
9         1109      S   12    Male
10        1110  David   33    Male
11        1111     Dw    3  Female
12        1112      Q   23    Male
13        1113      W   21  Female


In [180]:
data.to_pickle('student.pickle')

In [181]:
#定义资料集
df1 = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'])
df2 = pd.DataFrame(np.ones((3,4))*1, columns=['a','b','c','d'])
df3 = pd.DataFrame(np.ones((3,4))*2, columns=['a','b','c','d'])

#concat纵向合并
res = pd.concat([df1, df2, df3], axis=0)

#打印结果
print(res)

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0
0  2.0  2.0  2.0  2.0
1  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0


In [183]:

res = pd.concat([df1, df2, df3], axis=0, ignore_index=True) 
# ignore_index=True 重置 index 索引


print(res)

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0
6  2.0  2.0  2.0  2.0
7  2.0  2.0  2.0  2.0
8  2.0  2.0  2.0  2.0


In [184]:
df1 = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'], index=[1,2,3])
df2 = pd.DataFrame(np.ones((3,4))*1, columns=['b','c','d','e'], index=[2,3,4])

In [186]:
res = pd.concat([df1, df2], axis=0, join='outer')
# 默认 outer，相同 column 的上下合并，其他 column 独自成列
print(res)

     a    b    c    d    e
1  0.0  0.0  0.0  0.0  NaN
2  0.0  0.0  0.0  0.0  NaN
3  0.0  0.0  0.0  0.0  NaN
2  NaN  1.0  1.0  1.0  1.0
3  NaN  1.0  1.0  1.0  1.0
4  NaN  1.0  1.0  1.0  1.0


In [187]:
res = pd.concat([df1, df2], axis=0, join='inner') 
# 相同 column 合并，其他遗弃
print(res)

     b    c    d
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  0.0  0.0
2  1.0  1.0  1.0
3  1.0  1.0  1.0
4  1.0  1.0  1.0


In [188]:
# 重置 index
res = pd.concat([df1, df2], axis=0, join='inner', ignore_index=True)
print(res)

     b    c    d
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  1.0  1.0  1.0
4  1.0  1.0  1.0
5  1.0  1.0  1.0


In [189]:
df1 = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'])
df2 = pd.DataFrame(np.ones((3,4))*1, columns=['a','b','c','d'])
df3 = pd.DataFrame(np.ones((3,4))*1, columns=['a','b','c','d'])
s1 = pd.Series([1,2,3,4], index=['a','b','c','d'])

res = df1.append(df2, ignore_index=True)
print(res)

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0


In [191]:
res = df1.append([df2,df3], ignore_index=True) #  同时合并2个 df
print(res)

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0
6  1.0  1.0  1.0  1.0
7  1.0  1.0  1.0  1.0
8  1.0  1.0  1.0  1.0


In [192]:
res = df1.append(s1, ignore_index=True) #  同时合并2个 df
print(res)

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  2.0  3.0  4.0


In [193]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                             'A': ['A0', 'A1', 'A2', 'A3'],
                             'B': ['B0', 'B1', 'B2', 'B3']})
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                              'C': ['C0', 'C1', 'C2', 'C3'],
                              'D': ['D0', 'D1', 'D2', 'D3']})

In [195]:
res = pd.merge(left, right, on='key') # 根据 key column 合并
print(res)

    A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3
